# Setting `True` will include all subclasses of the class, without having to specify them explicitly.
LANDCOVER_CLASSES = {
    "urban": {"building": True, "landuse": ["construction", "commercial"]},
    "water": {
        "natural": ["water", "bay"],
        "place": ["sea"],
        "leisure": ["swimming_pool"],
    },
    "waterway": {"waterway": ["river", "stream"]},
    "woodland": {"landuse": ["forest"]},
    "grassland": {
        "landuse": ["grass", "vineyard", "orchard", "village_green"],
        "natural": ["island", "wood", "wetland"],
        "leisure": ["park", "pitch", "garden", "golf_course", "dog_park", "disc_golf_course", "sports_centre", "track"],
    },
    "streets": {
        "highway": [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "cycleway",
            "residential",
            "service",
            "unclassified",
            "footway",
            "motorway_link",
            "pedestrian"
        ],
        "railway": True,
    },
    "beach": {"natural": ["beach"]},
    "parking": {"amenity": ["parking"]},
    "rock": {"natural": ["bare_rock"]},
    "other": {"man_made": ["pier"]},
}

STYLES = {
    "Peach": {  # e.g. Macau
        "urban": {
            "cmap": ["#FFC857", "#E9724C", "#C5283D"],
            "ec": "#2F3737",
            "lw": 0.5,
            "zorder": 4,
        },
        "water": {
            "fc": "#a1e3ff",
            "ec": "#85c9e6",
            "hatch": "ooo...",
            "hatch_c": "#2F3737",
            "lw": 1,
            "zorder": 1,
        },
        "grassland": {"fc": "#D0F1BF", "ec": "#2F3737", "lw": 1, "zorder": 2},
        "woodland": {"fc": "#64B96A", "ec": "#2F3737", "lw": 1, "zorder": 2},
        "streets": {"fc": "#2F3737", "zorder": 3},
        "other": {"fc": "#F2F4CB", "ec": "#2F3737", "lw": 1, "zorder": 3},
    },
    "Auburn": {  # e.g. Barcelona
        "urban": {
            "cmap": ["#433633", "#FF5E5B", "#FF5E5B"],
            "ec": "#2F3737",
            "lw": 0.5,
            "zorder": 5,
        },
        "water": {
            "fc": "#a8e1e6",
            "ec": "#2F3737",
            "hatch": "ooo...",
            "hatch_c": "#9bc3d4",
            "lw": 1,
            "zorder": 3,
        },
        "grassland": {
            "fc": "#8BB174",
            "ec": "#2F3737",
            "hatch": "ooo...",
            "hatch_c": "#A7C497",
            "lw": 1,
            "zorder": 1,
        },
        "woodland": {"fc": "#64B96A", "ec": "#2F3737", "lw": 1, "zorder": 2},
        "streets": {"fc": "#2F3737", "zorder": 4},
        "other": {"fc": "#F2F4CB", "ec": "#2F3737", "lw": 1, "zorder": 3},
    },
    "Citrus": {  # e.g. Würzburg
        "urban": {
            "cmap": ["#FFFF3F", "#F4D58D", "#F5CB5C"],
            "ec": "#2F3737",
            "lw": 0.5,
            "zorder": 5,
        },
        "water": {
            "fc": "#007F5F",
            "ec": "#2F3737",
            "lw": 1,
            "zorder": 3,
        },
        "grassland": {
            "fc": "#55A630",
            "ec": "#2F3737",
            "hatch": "ooo...",
            "hatch_c": "#80B918",
            "lw": 1,
            "zorder": 1,
        },
        "woodland": {"fc": "#80B918", "ec": "#2F3737", "lw": 1, "zorder": 2},
        "streets": {"fc": "#FFFFFF", "zorder": 4},
        "other": {"fc": "#EAE2B7", "ec": "#2F3737", "lw": 1, "zorder": 3},
    },
    "Flannel": {  # e.g. Heerhugowaard
        "urban": {
            "cmap": ["#433633", "#FF5E5B", "#FF5E5B"],
            "ec": "#2F3737",
            "lw": 0.5,
            "zorder": 5,
        },
        "water": {
            "fc": "#a8e1e6",
            "ec": "#9bc3d4",
            "hatch_c": "#2F3737",
            "hatch": "ooo...",
            "lw": 1,
            "zorder": 3,
        },
        "grassland": {
            "fc": "#8BB174",
            "ec": "#A7C497",
            "hatch": "ooo...",
            "hatch_c": "#2F3737",
            "lw": 1,
            "zorder": 1,
        },
        "woodland": {"fc": "#64B96A", "ec": "#2F3737", "lw": 1, "zorder": 2},
        "streets": {"fc": "#2F3737", "zorder": 4},
        "other": {"fc": "#F2F4CB", "ec": "#2F3737", "lw": 1, "zorder": 3},
    },
    "Abraca Redencao": 
    {   'grassland': {'ec': '#000', 'lw': 1, 'zorder': 3},
        'streets': {'ec': '#2a3037', 'fc': '#ffefd5', 'lw': 1, 'zorder': 4},
        'urban': {'cmap': ['#fff'], 'ec': '#000', 'lw': 0.5, 'zorder': 5},
        'water': {'ec': '#2F3737', 'fc': '#a8e1e6', 'lw': 1, 'zorder': 3},
        'woodland': {'ec': '#2F3737', 'fc': '#64B96A', 'lw': 1, 'zorder': 2}},
    "Barcelona": 
    {   'grassland': {   'ec': '#2F3737',
                         'fc': '#8BB174',
                         'hatch': 'ooo...',
                         'hatch_c': '#A7C497',
                         'lw': 1,
                         'zorder': 1},
        'streets': {'ec': '#475657', 'fc': '#2F3737', 'lw': 0, 'zorder': 4},
        'urban': {   'cmap': ['#433633', '#FF5E5B'],
                     'ec': '#2F3737',
                     'lw': 0.5,
                     'zorder': 5},
        'water': {   'ec': '#2F3737',
                     'fc': '#a8e1e6',
                     'hatch': 'ooo...',
                     'hatch_c': '#9bc3d4',
                     'lw': 1,
                     'zorder': 3}},
    "Barcelona Plotter": 
    {   'grassland': {   'ec': '#2F3737',
                         'fc': 'None',
                         'hatch': 'ooo...',
                         'hatch_c': '#A7C497',
                         'lw': 1,
                         'zorder': 1},
        'streets': {'ec': '#475657', 'fc': 'None', 'lw': 1, 'zorder': 4},
        'urban': {   'cmap': ['#433633', '#FF5E5B'],
                     'ec': '#2F3737',
                     'fc': 'None',
                     'lw': 1,
                     'zorder': 5},
        'water': {   'ec': '#2F3737',
                     'fc': 'None',
                     'hatch': 'ooo...',
                     'hatch_c': '#9bc3d4',
                     'lw': 1,
                     'zorder': 3}},
    "Cb Bf F": 
    {   'grassland': {'ec': '#8ab58a', 'fc': '#a9d1a9', 'lw': 1, 'zorder': 1},
        'streets': {'ec': '#2F3737', 'fc': '#F1E6D0', 'lw': 1.5, 'zorder': 3},
        'urban': {'cmap': ['#fff'], 'ec': '#2F3737', 'lw': 1, 'zorder': 4},
        'water': {'ec': '#6da8c2', 'fc': '#92D5F2', 'lw': 1, 'zorder': 2},
        'woodland': {'ec': '#658a76', 'fc': '#78A58D', 'lw': 1, 'zorder': 1}},
    "Default": 
    {   'beach': {   'ec': '#2F3737',
                     'fc': '#FCE19C',
                     'hatch': 'ooo...',
                     'hatch_c': '#d4d196',
                     'lw': 1,
                     'zorder': 3},
        'grassland': {   'ec': '#2F3737',
                         'fc': '#8BB174',
                         'hatch': 'ooo...',
                         'hatch_c': '#A7C497',
                         'lw': 1,
                         'zorder': 1},
        'parking': {'ec': '#2F3737', 'fc': '#F2F4CB', 'lw': 1, 'zorder': 3},
        'rock': {'ec': '#2F3737', 'fc': '#BDC0BA', 'lw': 1, 'zorder': 6},
        'streets': {'ec': '#475657', 'fc': '#2F3737', 'lw': 0, 'zorder': 4},
        'urban': {   'cmap': ['#433633', '#FF5E5B'],
                     'ec': '#2F3737',
                     'lw': 0.5,
                     'zorder': 5},
        'water': {   'ec': '#2F3737',
                     'fc': '#a8e1e6',
                     'hatch': 'ooo...',
                     'hatch_c': '#9bc3d4',
                     'lw': 1,
                     'zorder': 99},
        'waterway': {   'ec': '#2F3737',
                        'fc': '#a8e1e6',
                        'hatch': 'ooo...',
                        'hatch_c': '#9bc3d4',
                        'lw': 1,
                        'zorder': 200},
        'woodland': {'ec': '#2F3737', 'fc': '#64B96A', 'lw': 1, 'zorder': 2}},
    "Heerhugowaard": 
    {   'beach': {   'ec': '#2F3737',
                     'fc': '#FCE19C',
                     'hatch': 'ooo...',
                     'hatch_c': '#d4d196',
                     'lw': 1,
                     'zorder': 3},
        'grassland': {   'ec': '#2F3737',
                         'fc': '#8BB174',
                         'hatch': 'ooo...',
                         'hatch_c': '#A7C497',
                         'lw': 1,
                         'zorder': 1},
        'parking': {'ec': '#2F3737', 'fc': '#F2F4CB', 'lw': 1, 'zorder': 3},
        'streets': {'ec': '#475657', 'fc': '#2F3737', 'lw': 0, 'zorder': 4},
        'urban': {   'cmap': ['#433633', '#FF5E5B'],
                     'ec': '#2F3737',
                     'lw': 0.5,
                     'zorder': 5},
        'water': {   'ec': '#2F3737',
                     'fc': '#a8e1e6',
                     'hatch': 'ooo...',
                     'hatch_c': '#9bc3d4',
                     'lw': 1,
                     'zorder': 3},
        'woodland': {'ec': '#2F3737', 'fc': '#64B96A', 'lw': 1, 'zorder': 2}},
    "Macao": 
    {   'grassland': {'ec': '#2F3737', 'fc': '#D0F1BF', 'lw': 1, 'zorder': 1},
        'parking': {'ec': '#2F3737', 'fc': '#F2F4CB', 'lw': 1, 'zorder': 3},
        'streets': {'ec': '#475657', 'fc': '#2F3737', 'lw': 0, 'zorder': 3},
        'urban': {   'cmap': ['#FFC857', '#E9724C', '#C5283D'],
                     'ec': '#2F3737',
                     'lw': 0.5,
                     'zorder': 4},
        'water': {   'ec': '#2F3737',
                     'fc': '#a1e3ff',
                     'hatch': 'ooo...',
                     'hatch_c': '#85c9e6',
                     'lw': 1,
                     'zorder': 2},
        'woodland': {'ec': '#2F3737', 'fc': '#64B96A', 'lw': 1, 'zorder': 1}},
    "Minimal": 
    {   'streets': {'fc': '#000', 'lw': 0, 'zorder': 4},
        'urban': {'ec': '#000', 'fc': '#fff', 'lw': 0.5, 'zorder': 5}},
    "Plotter": 
    {   'urban': {'ec': '#000000', 'fc': 'None', 'lw': 1, 'zorder': 5},
        'streets': {'ec': '#000000', 'fc': 'None', 'lw': 1, 'zorder': 4},
        'water': {'ec': '#000000', 'fc': 'None', 'lw': 1, 'zorder': 3},
        'woodland': {'ec': '#000000', 'fc': 'None', 'lw': 1, 'zorder': 2},
        'grassland': {'ec': '#000000', 'fc': 'None', 'lw': 1, 'zorder': 1}},
    "Tijuca": 
    {   'beach': {   'ec': '#EBD499',
                     'fc': '#F2E3BC',
                     'hatch': 'ooo...',
                     'lw': 0,
                     'zorder': 2},
        'grassland': {   'ec': '#AEB441',
                         'fc': '#D2D68D',
                         'hatch': 'ooo...',
                         'lw': 0,
                         'zorder': 3},
        'streets': {   'ec': '#706f6f',
                       'fc': '#898989',
                       'hatch': 'ooo...',
                       'lw': 0,
                       'zorder': 3},
        'urban': {'ec': '#E7A89C', 'fc': '#E7A89C', 'lw': 0, 'zorder': 0},
        'water': {   'ec': '#59adcf',
                     'fc': '#6CCFF6',
                     'hatch': 'ooo...',
                     'lw': 0,
                     'zorder': 2}},
}

STREETS_WIDTH = {
    "motorway": 4,
    "trunk": 4,
    "primary": 3.5,
    "primary_link": 3.5,
    "motorway_link": 3,
    "secondary": 3,
    "secondary_link": 3,
    "tertiary": 2.5,
    "tertiary_link": 2.5,
    "cycleway": 2.5,
    "residential": 2,
    "service": 1.5,
    "unclassified": 1.5,
    "pedestrian": 1.5,
    "footway": 0.7,
}
